/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.san.voidlauncher.frames;

/**
 *
 * @author Usuario
 */
public class ModpackPanel extends javax.swing.JPanel {
    private boolean isInstalled;

    /**
     * Creates new form ModpackPanel
     */
    public ModpackPanel(String mpName, String mpVersion, boolean isInstalled) {
        initComponents();
        prepare(mpName, mpVersion, isInstalled);
    }
    
    private void prepare(String mpName, String mpVersion, boolean isInstalled) {
        this.isInstalled = isInstalled;
        updateIsInstalled();
        modpackName.setText(mpName);
        modpackVersion.setText(mpVersion);
    }
    
    private void updateIsInstalled() {
        installButton.setEnabled(!isInstalled);
        selectButton.setEnabled(isInstalled);
    }
    
    public boolean isInstalled() {
        return this.isInstalled;
    }
    
    public void setInstalled(boolean val) {
        this.isInstalled = val;
        updateIsInstalled();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modpackName = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        installButton = new javax.swing.JButton();
        modpackVersion = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(180, 100));
        setMinimumSize(new java.awt.Dimension(180, 100));
        setPreferredSize(new java.awt.Dimension(180, 100));

        modpackName.setText("Modpack");

        selectButton.setText("Seleccionar");
        selectButton.setEnabled(false);

        installButton.setText("Instalar");

        modpackVersion.setText("ver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modpackName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(installButton))
                    .addComponent(modpackVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modpackName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modpackVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(installButton)
                    .addComponent(selectButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton installButton;
    private javax.swing.JLabel modpackName;
    private javax.swing.JLabel modpackVersion;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
